version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    # Không cần ánh xạ port ra ngoài vì chỉ sử dụng nội bộ (Nginx reverse proxy sẽ tiếp nhận request từ bên ngoài)
    expose:
      - "3000"
    restart: always
    networks:
      - app-network-1.0

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Ánh xạ port 80 của VPS đến port 80 trong container Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
    restart: always
    networks:
      - app-network-1.0

networks:
  app-network-1.0:
    driver: bridge
