version: "3.8"

services:
  nextjs:
    image: nguyenhuykhai/web3-app:latest
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    restart: always
    networks:
      - app-network-1.0

  nginx:
    image: nguyenhuykhai/red-envelope-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always
    networks:
      - app-network-1.0

networks:
  app-network-1.0:
    driver: bridge
