name: Deploy Next.js to Azure VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Next.js Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO_NEXTJS }}:latest .
          docker tag ${{ secrets.DOCKER_REPO_NEXTJS }}:latest ${{ secrets.DOCKER_REPO_NEXTJS }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REPO_NEXTJS }}:latest
          docker push ${{ secrets.DOCKER_REPO_NEXTJS }}:${{ github.sha }}

      - name: SSH to VPS and Restart Next.js Container
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/nextjs/red-envelope-docker
            docker-compose pull nextjs
            docker stop red-envelope-docker-nextjs-1
            docker rm red-envelope-docker-nextjs-1
            docker-compose up -d nextjs
            docker system prune -f
          EOF
